apiVersion: v1
kind: Service
metadata:
  name: multi-cloud-devsecops-platform
  namespace: multi-cloud-capstone
spec:
  selector:
    app: multi-cloud-devsecops-platform
  ports:
    - port: 80
      targetPort: 8080
  type: ClusterIP
